Candidate.Web/Areas/Dashboard/Controllers/ConfigurationController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Candidate.Areas.Dashboard.Models;
using Candidate.Core.Configurations;
using Candidate.Core.Model;
using Candidate.Core.Model.Configurations;
using Candidate.Core.Settings;
using Candidate.Infrustructure.Filters;

namespace Candidate.Areas.Dashboard.Controllers
{
    [Authorize]
    public class ConfigurationController : Controller
    {
        private readonly ISettingsManager _settingsManager;
        private readonly IConfigurationsFactory _configurationsFactory;

        public ConfigurationController(ISettingsManager settingsManager, IConfigurationsFactory configurationsFactory)
        {
            _settingsManager = settingsManager;
            _configurationsFactory = configurationsFactory;
        }

        [HttpGet]
        [AddViewNameAndHash]
        public ActionResult Index(string id)
        {
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(new NewConfigurationModel());
        }

        [HttpPost]
        public ActionResult Add(NewConfigurationModel model)
        {
            if (ModelState.IsValid)
            {
                var configuration = _configurationsFactory.CreateConfiguration(
                    model.SelectedType,
                    SubstitutePunctuationWithDashes(model.Name),
                    model.Name);

                _settingsManager.SaveConfiguration(configuration);

                return RedirectToAction("Index", new { controller = "Dashboard" });
            }

            return View(model);
        }

        // TODO: ABE move to extension method
        private string SubstitutePunctuationWithDashes(string title)
        {
            var titleWithoutPunctuation = new string(title.Where(c => !char.IsPunctuation(c)).ToArray());
            return titleWithoutPunctuation.ToLower().Trim().Replace(" ", "-");
        }

        [HttpGet, AddViewNameAndHash]
        public ActionResult Pre(string id)
        {
            throw new NotImplementedException();

            //var currentConfiguration = _settingsManager.ReadSettings<ConfigurationsList>();
            //var siteConfiguration = currentConfiguration.Configurations.Where(c => c.Id == id).SingleOrDefault();

            //return View(siteConfiguration.Pre);
        }

        [HttpPost]
        public ActionResult Pre(string id, Pre config)
        {
            throw new NotImplementedException();

            //if (ModelState.IsValid)
            //{
            //    _settingsManager.SaveSiteConfiguration(id, c => c.Pre = config);
            //    return Json(new { success = true });
            //}

            //return Json(new { success = false });
        }

        [HttpGet, AddViewNameAndHash]
        public ActionResult Github(string id)
        {
            throw new NotImplementedException();

            //var currentConfiguration = _settingsManager.ReadSettings<ConfigurationsList>();
            //var siteConfiguration = currentConfiguration.Configurations.Where(c => c.Id == id).SingleOrDefault();

            //return View(siteConfiguration.Github);
        }

        [HttpPost]
        public ActionResult Github(string id, Github config)
        {
            throw new NotImplementedException();

            //if (ModelState.IsValid)
            //{
            //    _settingsManager.SaveSiteConfiguration(id, c => c.Github = config);
            //    return Json(new { success = true });
            //}

            //return Json(new { success = false });
        }

        [HttpGet, AddViewNameAndHash]
        public ActionResult Iis(string id)
        {
            throw new NotImplementedException();

            //var currentConfiguration = _settingsManager.ReadSettings<ConfigurationsList>();
            //var siteConfiguration = currentConfiguration.Configurations.Where(c => c.Id == id).SingleOrDefault();

            //return View(siteConfiguration.Iis ?? new Iis());
        }

        [HttpPost]
        public ActionResult Iis(string id, Iis config)
        {
            throw new NotImplementedException();

            //if (ModelState.IsValid)
            //{
            //    _settingsManager.SaveSiteConfiguration(id, c => c.Iis = config);
            //    return Json(new { success = true });
            //}

            //return Json(new { success = false });
        }

        [HttpGet, AddViewNameAndHash]
        public ActionResult Solution(string id)
        {
            throw new NotImplementedException();

            //var currentConfiguration = _settingsManager.ReadSettings<ConfigurationsList>();
            //var siteConfiguration = currentConfiguration.Configurations.Where(c => c.Id == id).SingleOrDefault();

            //return View(siteConfiguration.Solution ?? new Solution());
        }

        [HttpPost]
        public ActionResult Solution(string id, Solution config)
        {
            throw new NotImplementedException();

            //if (ModelState.IsValid)
            //{
            //    _settingsManager.SaveSiteConfiguration(id, c => c.Solution = config);
            //    return Json(new { success = true });
            //}

            //return Json(new { success = false });
        }

        [HttpGet, AddViewNameAndHash]
        public ActionResult Post(string id)
        {
            throw new NotImplementedException();

            //var currentConfiguration = _settingsManager.ReadSettings<ConfigurationsList>();
            //var siteConfiguration = currentConfiguration.Configurations.Where(c => c.Id == id).SingleOrDefault();

            //return View(siteConfiguration.Post);
        }

        [HttpPost]
        public ActionResult Post(string id, Post config)
        {
            throw new NotImplementedException();

            //if (ModelState.IsValid)
            //{
            //    _settingsManager.SaveSiteConfiguration(id, c => c.Post = config);
            //    return Json(new { success = true });
            //}

            //return Json(new { success = false });
        }

        [HttpGet, AddViewNameAndHash]
        public ActionResult Delete(string id)
        {
            return View(new DeleteJobModel { JobName = id });
        }

        [HttpPost]
        public ActionResult Delete(DeleteJobModel deleteJob)
        {
            throw new NotImplementedException();

            //if (ModelState.IsValid)
            //{
            //    _settingsManager.DeleteSiteConfiguration(deleteJob.Id);
            //    return RedirectToAction("Index", "Dashboard");
            //}

            //return View(deleteJob);
        }


    }
}

Candidate.Web/Areas/Dashboard/Controllers/SetupController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Candidate.Areas.Dashboard.Models;
using Candidate.Core.Log;
using Candidate.Core.Model;
using Candidate.Core.Model.Configurations;
using Candidate.Core.Settings;
using Candidate.Core.Setup;
using Candidate.Core.Utils;
using Candidate.Infrustructure.Error;
using Candidate.Infrustructure.Filters;
using Newtonsoft.Json;

namespace Candidate.Areas.Dashboard.Controllers
{

    [Authorize]
    [HandleJsonError]
    public class SetupController : Controller
    {
        private ISettingsManager _settingsManager;
        private ISetupFactory _setupFactory;
        private ILoggerFactory _loggerFactory;
        private IDirectoryProvider _directoryProvider;

        public SetupController(ISettingsManager settingsManager, ISetupFactory setupFactory, ILoggerFactory loggerFactory, IDirectoryProvider directoryProvider)
        {
            _settingsManager = settingsManager;
            _setupFactory = setupFactory;
            _loggerFactory = loggerFactory;
            _directoryProvider = directoryProvider;
        }

        [HttpGet]
        public ActionResult Setup(string jobName)
        {
            throw new NotImplementedException();

            //ViewBag.Id = jobName;

            //var currentConfiguration = _settingsManager.ReadSettings<ConfigurationsList>();
            //var siteConfiguration = currentConfiguration.Configurations.Where(c => c.Id == jobName).SingleOrDefault();

            //if (!siteConfiguration.IsConfigured())
            //{
            //    return View("NotConfigured");
            //}

            //return View();
        }

        [HttpPost]
        public ActionResult StartSetup(string jobName)
        {
            throw new NotImplementedException();

            //var currentSettings = _settingsManager.ReadSettings<ConfigurationsList>().Configurations.Where(c => c.Id == jobName).SingleOrDefault();
            //if (currentSettings == null)
            //{
            //    throw new Exception(string.Format("Can't create setup for non-existing job: {0}", jobName));
            //}

            //return RunDeployAndLog(jobName, currentSettings);
        }

        [HttpPost]
        [ValidateToken]
        public ActionResult Hook(string jobName, string token, string payload)
        {
            throw new NotImplementedException();
            //var currentSettings = _settingsManager.ReadSettings<ConfigurationsList>().Configurations.Where(c => c.Id == jobName).SingleOrDefault();
            //if (currentSettings == null)
            //{
            //    throw new Exception(string.Format("Can't create setup for non-existing job: {0}", jobName));
            //}

            //// TODO: move this serialization to service
            //var payloadDeserialized = JsonConvert.DeserializeObject<GithubHookPayload>(payload);
            //var githubConfiguration = currentSettings.Github;

            //if (!IsHookForBranch(payloadDeserialized.Branch, githubConfiguration))
            //{
            //    return null;
            //}

            //return RunDeployAndLog(jobName, currentSettings);
        }

        private static bool IsHookForBranch(string payload, Github githubConfiguration)
        {
            return payload.Equals(githubConfiguration.Branch);
        }

        private ActionResult RunDeployAndLog(string jobName, VisualStudioConfiguration currentSettings)
        {
            _directoryProvider.SiteName = jobName;

            using (var logger = _loggerFactory.CreateLogger())
            {
                var setup = _setupFactory.CreateSetup();
                var result = setup.RunForConfig(logger, currentSettings);

                return Json(new { success = true, result = result });
            }
        }

    }
}

Candidate.Web/Areas/Dashboard/Views/Configuration/Configure.cshtml
@model Candidate.Areas.Dashboard.Models.JobConfigurationModel

@{
    ViewBag.Title = "Configure";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";    
}

<div id="internal-nagivation">
    <h2>Build > Jobs > Configure</h2>
    <div class="right">@Html.ActionLink("Back to dashboard", "Index", new { area = "Dashboard", controller = "Dashboard" } )</div>
    <div class="clear"></div>
</div>

<div class="grey-container">

<div class="configuration">

    <div class="configuration-line">
        <div id="scm-configuration" class="configuration-box" data-source="@Url.Action("ConfigureGithub", new { area = "Dashboard", controller = "Configuration", jobName = ViewBag.JobName })">
            <p>GITHUB</p>
        </div>

        <div id="iis-configuration" class="configuration-box" data-source="@Url.Action("ConfigureIis", new { area = "Dashboard", controller = "Configuration", jobName = ViewBag.JobName })">
            <p>IIS</p>
        </div>
    </div>
</div>
<div class="dialog"></div>

@section Scripts {
    <script src="@Url.Content("~/Scripts/jquery.blockUI.js")" type="text/javascript"></script>    
    <script src="@Url.Content("~/Scripts/jquery.form.js")" type="text/javascript"></script>    
    <script src="@Url.Content("~/Scripts/Controllers/controller.configure.js")" type="text/javascript"></script>
}

Candidate.Web/Areas/Dashboard/Views/Configuration/ConfigureGithub.cshtml
@model Candidate.Areas.Dashboard.Models.GithubModel

<h2>Github repository configuration</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary();
                                   
    <fieldset>
        <div id="github-url">
            @Html.LabelFor(m => m.Url)
            @Html.TextBoxFor(m => m.Url)
        </div>
        <div id="github-branch">
            @Html.LabelFor(m => m.Branch)
            @Html.TextBoxFor(m => m.Branch)
        </div>
    </fieldset>
    <div class="clear"></div>
    <button type="submit" class="minimal">Save config</button>
    <button type="reset" class="minimal">Reset</button>    
}

Candidate.Web/Areas/Dashboard/Views/Configuration/ConfigureIis.cshtml
@model Candidate.Areas.Dashboard.Models.IisModel

<h2>IIS web site configuration</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary();
                                   
    <fieldset>
        <div id="iis-name">
            @Html.LabelFor(m => m.SiteName)
            @Html.TextBoxFor(m => m.SiteName)
        </div>
    </fieldset>

    <div class="clear"></div>    
    <button type="submit" class="minimal">Save config</button>
    <button type="reset" class="minimal">Reset</button>    
    
}

Candidate.Web/Areas/Dashboard/Views/Configuration/Delete.cshtml
@model Candidate.Areas.Dashboard.Models.DeleteJobModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";    
}

<div id="internal-nagivation">
    <h2>Build > Sites > Delete</h2>
    <div class="right">@Html.ActionLink("Back to dashboard", "Index", new { area = "Dashboard", controller = "Dashboard" } )</div>
    <div class="clear"></div>
</div>

<div class="grey-container">
@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    @Html.HiddenFor(m => m.JobName);
    
    <p>
        Are you sure to delete <strong>@Model.JobName</strong> job?
    </p>
                                        
    <button type="submit" class="minimal">Delete</button>
} 
</div>

Candidate.Web/Areas/Dashboard/Views/Configuration/DeleteConfiguration.cshtml
@model Candidate.Areas.Dashboard.Models.DeleteJobModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";    
}

<div id="internal-nagivation">
    <h2>Build > Jobs > Delete</h2>
    <div class="right">@Html.ActionLink("Back to dashboard", "Index", new { area = "Dashboard", controller = "Dashboard" } )</div>
    <div class="clear"></div>
</div>

<div class="grey-container">
@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    @Html.HiddenFor(m => m.JobName);
    
    <p>
        Are you sure to delete <strong>@Model.JobName</strong> job?
    </p>
                                        
    <button type="submit" class="minimal">Delete</button>
} 
</div>

Candidate.Web/Areas/Dashboard/Views/Configuration/Github.cshtml
@model Candidate.Core.Model.Github
@{
    Layout = "~/Areas/Dashboard/Views/Shared/_Unobtrusive.cshtml";
}

<div class="dialog">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary();
                                   
        <fieldset>
            <legend>Github repository configuration</legend>
            <div id="github-url">
                @Html.LabelFor(m => m.Url)
                @Html.TextBoxFor(m => m.Url)
            </div>
            <div id="github-branch">
                @Html.LabelFor(m => m.Branch)
                @Html.TextBoxFor(m => m.Branch)
            </div>
            <div id="github-hook">
                @Html.LabelFor(m => m.Hook)
                @Html.TextBoxFor(m => m.Hook, new { @readonly = true, @Value = Url.Action("Hook", "Setup", new { area = "Dashboard", jobName = ViewBag.JobName, token = ViewBag.JobNameHash }, "http") } )            
            </div>
        </fieldset>
    
        <div class="right">
            <button type="submit" class="minimal">Save config</button>
            <button id="close" type="button" class="minimal">Close</button>    
        </div>

    }
</div>